### ISSUE TITLE
Compilation Error : undefined reference to `mDashInit'

### ISSUE THREAD

**Issue by ghost** [cesanta/mDash#8]
Arduino IDE 1.8.12
mdash 1.2.5

```
sketch\Minimal.ino.cpp.o:(.literal._Z5setupv+0x2c): undefined reference to `mDashInit'
sketch\Minimal.ino.cpp.o: In function `setup()':
C:\Program Files (x86)\Arduino\libraries\mDash-1.2.5\examples\Minimal/Minimal.ino:26: undefined reference to `mDashInit'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board ESP32 Dev Module.
```
It appears that libmdash.a seems to be a 32-bit elf library and not 64-bit. Thus, this library cannot be loaded by the IDE. Thus to solve the issue, I tried to use Arduino IDE V 1.8.10, and it worked. Pleas solve the issue for the latest Arduino IDE and please give the source code for library and not a ".a" file.

Thank You

**Comment by RobinsonLaw** [comment]
same issue in compile by platformIO

**Comment by shridattdudhat** [comment]
Code is compiled on Arduino 1.8.11 but it is not compiling on 1.8.13
------------------------------------------------------------------------------------

Library mDash has been declared precompiled:
Using precompiled library in C:\Users\Oizom\Documents\Arduino\libraries\mDash\src\esp32
The plaform does not support 'compiler.libraries.ldflags' for precompiled libraries.
sketch\Minimal.ino.cpp.o:(.literal._Z5setupv+0x2c): undefined reference to `mDashInit'
sketch\Minimal.ino.cpp.o: In function `setup()':
C:\Users\Oizom\Documents\Arduino\libraries\mDash\examples\Minimal/Minimal.ino:26: undefined reference to `mDashInit'
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\Oizom\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by cpq** [comment]
1. Find Arduino's esp32 `plaform.txt` file and change it like in [PR4209](https://github.com/espressif/arduino-esp32/pull/4209/commits/183964aa93b7039d11813fd60aba7e8170caa4b8)
2. Find `library.properties` file in the installed mDash library, and remove line `ldflags=-lmDash`
3. Restart Arduino IDE

**Comment by cpq** [comment]
Please see https://github.com/cesanta/mDash/issues/8

**Comment by cpq** [comment]
Please try the latest version - tested and works with Arduino 1.8.19
